"use strict";
const assert = require("node:assert/strict");
const fs = require("node:fs");
const vm = require("node:vm");
const crypto = require("node:crypto");
const read = path => fs.readFileSync(path, "utf8");
const html = read("web/speech-bubble-editor.html");
const js = read("web/quick-retouch.js");
const css = read("web/quick-retouch.css");
const core = read("web/quick-retouch-core.js");
const desktop = read("web/desktop/desktop-shell.js");
const blob = value => { const data = value.replace(/\r\n/g, "\n"); return crypto.createHash("sha1").update(`blob ${Buffer.byteLength(data)}\0`).update(data).digest("hex"); };
assert.equal(blob(core), "e20a3ac3425efaf4d394fb909500656265523004", "pure core must remain identical to pinned upstream");
assert.equal(blob(css), "ef380b1f2c1bd2119aded5a1184e9df6ad10186a", "CSS must remain identical to pinned upstream");
for (const [name, source] of [["quick-retouch.js", js], ["quick-retouch-core.js", core]]) new vm.Script(source, { filename: name });
for (const path of ["quick-retouch-core.js", "quick-retouch.js", "quick-retouch.css"]) assert.ok(html.includes(`./${path}?v=standalone-retouch-1`), path);
assert.ok(html.indexOf('data-left-section="background-removal"') < html.indexOf('data-left-section="comic-converter"'));
assert.ok(html.indexOf('data-left-section="comic-converter"') < html.indexOf('data-left-section="quick-retouch"'));
assert.ok(html.indexOf('data-left-section="quick-retouch"') < html.indexOf('data-left-section="bubbles"'));
assert.match(html, /initializeQuickRetouch\(\);/);
assert.match(html, /processLayerQuickRetouch/);
assert.match(html, /applyProcessedSingleImage\(blob,name,"quick-retouch",source\)/);
assert.match(html, /sourceContext\?null:/, "external source context protection must survive");
assert.match(html, /getMode:\(\)=>generalComicEditor\?\.isActive\(\)\?"comic_layout"/);
assert.match(js, /mode === "comic_layout" \? "comic_layout"/);
assert.match(js, /data-retouch-mode/);
assert.match(js, /sourceRevision/);
assert.match(js, /getDocumentId/);
assert.match(js, /new Worker|core\.renderStack/);
assert.match(js, /PREVIEW_LONG_EDGE = 920/);
assert.match(js, /MAX_HISTORY_BYTES = 512 \* 1024 \* 1024/);
assert.match(js, /MAX_HISTORY_STEPS = 32/);
for (const name of ["brush", "eraser", "lasso", "rectangle", "wand", "color_range", "eyedropper", "hand", "zoom"]) assert.ok(js.includes(`id: "${name}"`), name);
for (const feature of ["hue_saturation", "brightness_contrast", "ellipseMask", "data-retouch-curve", "data-retouch-quick-mask", "initialDocumentSnapshot", "source_kind: \"external-file\"", "releaseDocument", "event.stopPropagation()"])
  assert.ok(js.includes(feature), feature);
assert.doesNotMatch(js, /indexedDB|fetch\(|new WebSocket|XMLHttpRequest/, "retouch module must stay browser-local");
assert.match(desktop, /Open Quick Retouch/);
assert.match(html, /dialog\.quick-retouch-dialog\[open\]/, "host shortcuts must not leak into the modal");
assert.match(read(".github/workflows/validate.yml"), /node tests\/quick_retouch_browser_smoke.cjs/);
assert.match(read("README.md"), /内部の調整レイヤー・選択範囲・マスク・履歴は保存しません/);
console.log("quick_retouch_integration_test: OK");
